### ISSUE TITLE
Use enclosure URL as the GUID, if there isn't one

### ISSUE THREAD

**Issue by vpul** [RyanHirsch/partytime#15]
There are quite a few podcasts that still don't have guid, I wouldn't want to skip them.
Instead of skipping them altogether, could you instead use enclosure URL as GUID? 

https://github.com/RyanHirsch/partytime/blob/d2dbc8fa91866d2cce6e8c5437c0a1806683a121/src/parser/item.ts#L39

**Comment by RyanHirsch** [comment]
You're right, sorry I took so long to address this. Should be allowable with `parseFeed(xml, { allowMissingGuid: true })` now.
