### ISSUE TITLE
Add support for the <podcast:chat> element

### ISSUE THREAD

**Issue by mitchdowney** [RyanHirsch/partytime#31]
I don't think the spec is fully formalized, but Alecks mentioned he made an XMPP plugin that works with the <podcast:chat> element, and it'd be to cool to add XMPP chat support to Podverse when the tag is ready.

https://github.com/Podcastindex-org/podcast-namespace/blob/main/proposal-docs/chat/social.md

**Comment by RyanHirsch** [comment]
this has been fixed, thanks for the callout Mitch
