### ISSUE TITLE
Add <podcast:publisher> support

### ISSUE THREAD

**Issue by mitchdowney** [RyanHirsch/partytime#44]
Does Partytime support publisher? I'm not seeing it in the types.

https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#publisher

**Comment by mitchdowney** [comment]
I'm thinking that when a feed is a "publisher" feed, maybe partytime returns only the channel level data, and a prop named something like `remoteItems`?

When a feed is a publisher, my understanding is that it should not contain any regular `<item>` tags. Instead a publisher feed is a collection of references to remote items.

**Comment by RyanHirsch** [comment]
looks like #55  only added publisher tag support, still need to ensure a publisher feed can be consumed....
